### ISSUE TITLE
King (1966)

### ISSUE THREAD

**Issue by brycefrank** [brycefrank/allometric#100]
**Provide a citation of the publication you want us to add.**

```
@article{king1966site,
  title={Site index curves for Douglas-fir in the Pacific Northwest},
  author={King, James E},
  year={1966}
}
```

**Comment by biometrica** [comment]
@brycefrank I have a signed copy of the original publication.  Do you still need this one?

**Comment by brycefrank** [comment]
Hey Nate! A couple people have sent this one to me now. Happy to see the signed one any time of course ☺️

**Comment by biometrica** [comment]
@brycefrank sounds great to me and thanks for all the amazing work you are doing here on Github.  I am looking forward to pouring through your repos over then next few weeks.  I really appreciate how you are demonstrating the "new way" we can collaborate as a profession!  I would encourage you to seek chances to share this broadly at meetings like SOMENS and WMENS.

**Comment by brycefrank** [comment]
@biometrica Thanks, I am planning to present it in the future

**Comment by brycefrank** [comment]
Did not add height model
