### ISSUE TITLE
Cochran (1985)

### ISSUE THREAD

**Issue by brycefrank** [brycefrank/allometric#104]
**Provide a citation of the publication you want us to add.**
```
@book{cochran1985site,
  title={Site index, height growth, normal yields, and stocking levels for larch in Oregon and Washington},
  author={Cochran, PH},
  volume={424},
  year={1985},
  publisher={US Department of Agriculture, Forest Service, Pacific Northwest Forest and~…}
}
```

Tracks #88

https://www.fs.usda.gov/pnw/pubs/pnw_rn424.pdf

**Comment by brycefrank** [comment]
p. 21 item 5 gives the SI function

**Comment by biometrica** [comment]
Keep it coming, Frank! If you have any spare time (doubt it!) focus in on those FVS SI equations. Once you have the model coded up it’s a matter of just dubbing in parameters. This contribution would save our team a lot of headaches with respect to getting past 3rd party verification for our offset projects (currently the auditor must program up the SI equations and cross-verify; if you do it that stops happening).Nate Sent from my iPhoneOn May 28, 2023, at 11:31 AM, Bryce Frank ***@***.***> wrote:﻿
p. 21 item 5 gives the SI function

**Comment by brycefrank** [comment]
@biometrica Great, took a little break but back on the horse :)

**Comment by brycefrank** [comment]
Did not add volume or height functions
